### ISSUE TITLE
Spiders facing the wrong way

### ISSUE THREAD

**Issue by yambriz** [andrei923/DeadByDaylight#7]
![2020-05-02_16 21 10](https://user-images.githubusercontent.com/53658260/80894585-1fce9400-8c91-11ea-99e2-b7dea6a8a261.png)
 idk what to do the spider doesn't face the right way i have 2 arenas and they face the wrong way and i followed the tutorial and it still does it

**Comment by andrei923** [comment]
when you set the hook you must face the direction you want them to face.

**Comment by yambriz** [comment]
where do you have to stand

**Comment by yambriz** [comment]
because in the tutorial you stood behind it and i did that but it still does it do i have to face it in front?

**Comment by yambriz** [comment]
oof

**Comment by andrei923** [comment]
i tested it at it works fine 
![image](https://user-images.githubusercontent.com/29291628/81498245-77da4b80-92cc-11ea-8d5e-aa5d5c5a0d08.png)

**Comment by yambriz** [comment]
thats what i did but for some reason they face backwards
