### ISSUE TITLE
script error

### ISSUE THREAD

**Issue by BellCocoa** [andrei923/DeadByDaylight#8]
I'm going to use it in spigot 1.12.2.
All necessary plugins are already installed.
https://pastebin.com/AvS7SFj1

**Comment by andrei923** [comment]
make sure you use the latest version of LeafSK https://github.com/andrei923/LeafSK/releases

**Comment by BellCocoa** [comment]
Resolved. Thank you.
I have one more question.
When I add a generator, all of the IDs are set to 1.

**Comment by BellCocoa** [comment]
I got the error again.
https://pastebin.com/hPTHhkmJ

**Comment by BellCocoa** [comment]
New error...
https://pastebin.com/AfHLwAEV

**Comment by andrei923** [comment]
in skript config enable this.

> disable variable conflict warnings: true

**Comment by andrei923** [comment]
fixed generators setup in latest release
